### ISSUE TITLE
Add fancytree.js to dependencies

### ISSUE THREAD

**Issue by ZAYEC77** [wbraganca/yii2-fancytree-widget#4]
Why you don't add `"bower-asset/fancytree": "*"` in dependencies of `composer.json`?

**Comment by georgezim85** [comment]
Hello, guys.

When I do composer uptate after add
"wbraganca/yii2-fancytree-widget": "*"
in "require-dev", it shows:
Problem 1
    - Installation request for wbraganca/yii2-fancytree-widget * -> satisfiable by wbraganca/yii2-fancytree-widget[dev-master].
    - wbraganca/yii2-fancytree-widget dev-master requires bower-asset/fancytree * -> no matching package found.


How can I fix it? I searched on packagist.org for bower-asset/fancytree and it really doesn't exist.

**Comment by akimapilot** [comment]
any update on this?

**Comment by georgezim85** [comment]
I solved my problem inserting this in composer.json (require): 
"dantleech/fancytree": "dev-composer"

**Comment by andrwsv** [comment]
I have the same problem , I put the code of  @georgezim85  and dont work.
this is the error of composer update 👍 

> Problem 1
    - wbraganca/yii2-fancytree-widget 1.0.1 requires bower-asset/fancytree >=2.12 -> no matching package found.
    - wbraganca/yii2-fancytree-widget 1.0.0 requires bower-asset/fancytree * -> no matching package found.
    - Installation request for wbraganca/yii2-fancytree-widget * -> satisfiable by wbraganca/yii2-fancytree-widget[1.0.0, 1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems. 

>
