### ISSUE TITLE
How to define data source url.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [wbraganca/yii2-fancytree-widget#7]
How to define data source url, and sorry for the inconvenience no documentation about it,

Thks,

**Comment by demogorgorn** [comment]
<?= \wbraganca\fancytree\FancytreeWidget::widget([
        'options' =>[
            /*'id' => 'tree',*/
            'source' => Category::getMenuStructure(false, true),
            'extensions' => ['dnd'],
            'dnd' => [
                'preventVoidMoves' => true,
                'preventRecursiveMoves' => true,
                'autoExpandMS' => 400,
                'dragStart' => new \yii\web\JsExpression('function(node, data) {
                    return true;
                }'),
                'dragEnter' => new \yii\web\JsExpression('function(node, data) {
                    return true;
                }'),
                'dragDrop' => new \yii\web\JsExpression('function(node, data) {
                    data.otherNode.moveTo(node, data.hitMode);
                }'),
            ],
            'activate' => new \yii\web\JsExpression("function(node, data) {
                if ($('#delete-button').is(':disabled') == true)
                    $('#delete-button').removeAttr('disabled');
            }"),

        ]
    ]); ?>

**Comment by tecnologiaterabyte** [comment]
according understand you would like this,

Code Example:

    $data = [
        ['title' => 'Node 1', 'key' => 1, 'url' => 'your-url-here'],
        ['title' => 'Folder 2', 'key' => '2', 'folder' => true, 'children' => [
            ['title' => 'Node 2.1', 'key' => '3', 'url' => 'your-url-here'],
            ['title' => 'Node 2.2', 'key' => '4', 'url' => 'your-url-here']
        ]]
    ];

**Comment by demogorgorn** [comment]
What do you want to do exactly? To add items from json or add them manually?

if manually:

```php
$data = [
    ['title' => 'Node 1', 'key' => 1, 'url' => 'your-url-here'],
    ['title' => 'Folder 2', 'key' => '2', 'folder' => true, 'children' => [
        ['title' => 'Node 2.1', 'key' => '3', 'url' => 'your-url-here'],
        ['title' => 'Node 2.2', 'key' => '4', 'url' => 'your-url-here']
    ]]
];

<?= \wbraganca\fancytree\FancytreeWidget::widget([
        'options' =>[
            /*'id' => 'tree',*/
            'source' => $data,
            'extensions' => ['dnd'],
            'dnd' => [
                'preventVoidMoves' => true,
                'preventRecursiveMoves' => true,
                'autoExpandMS' => 400,
                'dragStart' => new \yii\web\JsExpression('function(node, data) {
                    return true;
                }'),
                'dragEnter' => new \yii\web\JsExpression('function(node, data) {
                    return true;
                }'),
                'dragDrop' => new \yii\web\JsExpression('function(node, data) {
                    data.otherNode.moveTo(node, data.hitMode);
                }'),
            ],
            'activate' => new \yii\web\JsExpression("function(node, data) {
                if ($('#delete-button').is(':disabled') == true)
                    $('#delete-button').removeAttr('disabled');
            }"),

        ]
    ]); ?>
``` 

if via json:

```php
<?= \wbraganca\fancytree\FancytreeWidget::widget([
        'options' =>[
            /*'id' => 'tree',*/
            'source' => [ 
                'url' => 'http://your-website.com/data-tree.json'
            ],
            'extensions' => ['dnd'],
            'dnd' => [
                'preventVoidMoves' => true,
                'preventRecursiveMoves' => true,
                'autoExpandMS' => 400,
                'dragStart' => new \yii\web\JsExpression('function(node, data) {
                    return true;
                }'),
                'dragEnter' => new \yii\web\JsExpression('function(node, data) {
                    return true;
                }'),
                'dragDrop' => new \yii\web\JsExpression('function(node, data) {
                    data.otherNode.moveTo(node, data.hitMode);
                }'),
            ],
            'activate' => new \yii\web\JsExpression("function(node, data) {
                if ($('#delete-button').is(':disabled') == true)
                    $('#delete-button').removeAttr('disabled');
            }"),

        ]
    ]); ?>
```

**Comment by tecnologiaterabyte** [comment]
thanks for your answer

**Comment by tecnologiaterabyte** [comment]
Sorry for the inconvenience as I can add icons lei according to documentation of fancytree is:

                'glyph' => [
                    'map:' => [
                        'folder' => 'glyphicon glyphicon-folder-close',
                    ],
                ]

But does not work there are another way to add icons,

Thks,
