### ISSUE TITLE
add icon custom.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [wbraganca/yii2-fancytree-widget#8]
Sorry for the inconvenience as I can add icons according to documentation of fancytree is:

                'glyph' => [
                    'map:' => [
                        'folder' => 'glyphicon glyphicon-folder-close',
                    ],
                ]

But does not work there are another way to add icons,

Thks,

**Comment by demogorgorn** [comment]
```php

        'map' =>

```

without ":"

**Comment by tecnologiaterabyte** [comment]
ok that would serve me to map icons fancytree, but I'm making a menu and want to add an icon to each link of the menu, is there any way to do.

**Comment by demogorgorn** [comment]
It is possible to add custom attribute to each item and then process it in javascript.

I'll put here a small example of processing custom attributes (not exactly what you need, because i have not the task to place different icons for items),

here i'm forming a tree where each item has a custom attribute "page":
```php
                                  $item = array(
			                'key' => $page['id'],
			                'title' => $page['header'],
			                'folder' => false,
			                'page' => true,
			                'ordering' => $page['ordering'],
			                'created' => $page['created'],
			            );
```

later in my view (i'm using an mvc) i place following js code:

```javascript

          'dragEnter' => 'function(node, data) { 
                if ((data.otherNode.data.page == true) && (data.node.getParent().title == "root")) { 
                    return ["over"];
                } else 
                if (!data.node.isFolder()) {
                    return ["before","after"]; 
                } else
                    return true; 
            }',

```

Using the attribute "page" i decide what mechanism of dnd should be used for the current dragged item.

So, in initialization method you can override default icons depending on the custom attribute.

The second way is to style using css - http://wwwendt.de/tech/fancytree/demo/#sample-theming.html

The third way is quite similar to my - http://wwwendt.de/tech/fancytree/demo/#sample-ext-bootstrap.html

**Comment by tecnologiaterabyte** [comment]
Ready and achieves finally replace the class icon, as I am using the extension for a menu, I need only one thing, and that is when I open a menu option that has submenu and give the link, it closes the option the menu, as I make is deployed.

My Code:

        <?php echo \wbraganca\fancytree\FancytreeWidget::widget([
            'options' =>[
                'source' => $data,
                'extensions' => ['dnd'],
                'dnd' => [
                    'preventVoidMoves' => true,
                    'preventRecursiveMoves' => true,
                    'autoCollapse' => true,
                    'dragStart' => new \yii\web\JsExpression('function(node, data) {
                        return true;
                    }'),
                    'dragEnter' => new \yii\web\JsExpression('function(node, data) {
                        return true;
                    }'),
                    'dragDrop' => new \yii\web\JsExpression('function(node, data) {
                        data.otherNode.moveTo(node, data.hitMode);
                    }'),
                ],
                'activate' => new \yii\web\JsExpression('function(node, data) {
                    var node = data.node;
                    if (node.data.url) {
                        window.location=(node.data.url);
                    }
                 }'),
                'renderNode' =>  new \yii\web\JsExpression('function(node, data) {
                     var node = data.node;
                     if(node.data.cstrender){
                        var $span = $(node.span);
                        $span
                            .find("> span.fancytree-icon")
                            .removeClass("fancytree-icon icon-file-alt")
                            .addClass(node.data.iconcustom);
                     }
                }'),
            ]
        ]); ?>

Option Menu: (http://example.com/admin)

![menu_01](https://cloud.githubusercontent.com/assets/4957021/6074073/4b19edfe-ad89-11e4-8e9a-d1bb33edfb4b.jpg)

selecting the submenu option definitions.:

![menu_02](https://cloud.githubusercontent.com/assets/4957021/6074091/7df78150-ad89-11e4-80a3-08f487742f26.jpg)

Option Selected Turnos:

![menu_03](https://cloud.githubusercontent.com/assets/4957021/6074102/b6589282-ad89-11e4-849f-84a847259afc.jpg)

because the menu contains menus close, as I do to keep dropdown submenus.

Thks.

**Comment by tecnologiaterabyte** [comment]
Solved.
